


spring:
    profiles: dev
    application:
      name: cloudserver-config-client

eureka:
    client:
       service-url:
            defaultZone: http://eureka5401-dev:5401/eureka/



spring:
    profiles: test
    application:
      name: cloudserver-config-client

eureka:
    client:
       service-url:
            defaultZone: http://eureka5401-test:5401/eureka/